### ISSUE TITLE
[FlutterWeb] Buttons not working => Bold, Italic, Title (h1,h2,h3), List and Link

### ISSUE THREAD

**Issue by MayuriXx** [playmoweb/markdown-editable-textinput#2]
How time ? :D

**Comment by edouardouvrard** [comment]
Hi,
What issue do you have ?

**Comment by MayuriXx** [comment]
Excuse me for my late answer.
In flutter web : 

your button : bold/italic, title... don't work. I didn't test it in flutter mobile. 
Do you have developed this functions or not ?

**Comment by edouardouvrard** [comment]
We didn't test with Flutter Web, I reopen the issue.
Thanks

**Comment by clemenceroumy** [comment]
Hi, a new version of the package has been deployed, fixing your issue. 

However, Flutter currently has an issue with selecting in a TextInput that has several rows (see [this issue](https://github.com/flutter/flutter/issues/55627)). This issue has been solved on the master channel of Flutter (see [this PR](https://github.com/flutter/engine/pull/19924)) but is not yet available on the beta channel.
