### ISSUE TITLE
[Feature] add image/blockquote in textinput

### ISSUE THREAD

**Issue by sumitbhanushali** [playmoweb/markdown-editable-textinput#4]

**Comment by edouardouvrard** [comment]
blockquote can be easy to add but image can be more complicated.

We can easily convert an url of an image to `![Google logo](https://www.google.fr/images/srpr/logo11w.png "google logo")` for example and let you choose how you get this url ?

**Comment by sumitbhanushali** [comment]
> blockquote can be easy to add but image can be more complicated.
> 
> We can easily convert an url of an image to `![Google logo](https://www.google.fr/images/srpr/logo11w.png "google logo")` for example and let you choose how you get this url ?

And about local files?

**Comment by edouardouvrard** [comment]
I think we can follow the same rules of the markdown package https://pub.dev/packages/flutter_markdown#image-support

If you provide a compatible url and use this package to display your markdown this will be working.

**Comment by sumitbhanushali** [comment]
@edouardouvrard any update?

**Comment by edouardouvrard** [comment]
Not planned for the moment but you could start a PR if you want 👍

**Comment by codenameakshay** [comment]
I have added support for both in PR #15
