### ISSUE TITLE
Add Keyboard Action Bar Option

### ISSUE THREAD

**Issue by Nolence** [playmoweb/markdown-editable-textinput#8]
Hi!

I rewrote this library a bit to instead use an overlay entry to show an action bar above the keyboard and was wondering if you're interested in the idea of abstracting the action bar away so it can be used in the text field itself or as an overlay.

<img width="374" alt="Screen Shot 2020-08-25 at 5 45 10 PM" src="https://user-images.githubusercontent.com/29642168/91238897-537b7100-e6fb-11ea-8f65-e64616c73f9d.png">

I mean to eventually write a library that has the same functionality as [this javascript lib](https://simplemde.com/) so I'd love to help with this one rather than make my own.

**Comment by edouardouvrard** [comment]
Hi,
Can you make a PR and we can discuss about your change after we see it ?
Your idea look good to me

**Comment by Nolence** [comment]
Sure I'd love to. I'll try to have it by this weekend
